---
title: "图形高级定制"
output: 
  pdf_document: 
    extra_dependencies:
      ctex: UTF8  
    latex_engine: xelatex
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE,
  # cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)
```

# 字体

## 中文

```{r, fig.showtext=TRUE}
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    title = "鸢尾花数据的散点图",
    x = "萼片长度", y = "萼片宽度", colour = "鸢尾花类别"
  ) +
  theme_minimal(base_size = 10.54, base_family = "wqy-microhei")
```

图形里的字体，以矿大学位论文的要求为例，

1. 字体宋体，五号
2. 数字、字母字体都是 Times New Roman
3. 5 号字体对应 10.54pt，宋体此处采用思源宋体

```{r, fig.showtext=TRUE}
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    title = "鸢尾花数据的散点图",
    x = "萼片长度", y = "萼片宽度", colour = "鸢尾花类别"
  ) +
  theme_minimal(base_size = 10.54, base_family = "source-han-serif-cn") +
  theme(
    legend.text = element_text(family = "serif", size = 10.54),
    axis.text = element_text(family = "serif", size = 10.54)
    )
```

- 简单起见，字体为思源宋体，字号5号，英文和数字随思源宋体，不再另外设置，其实看不出来差别

```{r fig.showtext=TRUE}
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    title = "鸢尾花数据的散点图",
    x = "萼片长度", y = "萼片宽度", colour = "鸢尾花类别"
  ) +
  theme_minimal(base_size = 10.54, base_family = "source-han-serif-cn")
```

- 自定义中文字体

1. 标题：思源宋体加粗
2. 坐标轴标签：思源宋体
3. 图例：思源黑体

```{r, fig.showtext=TRUE, echo=TRUE}
# library(showtext)
# Install Source Han Sans font (by default Simplified Chinese)
# font_install(source_han_serif("CN")) # 思源宋体
# font_install(source_han_sans("CN"))  # 思源黑体
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    title = "鸢尾花数据的散点图",
    x = "萼片长度", y = "萼片宽度", colour = "鸢尾花类别"
  ) +
  theme(
    title = element_text(family = "source-han-sans-cn", face = "plain", size = 10.54),
    axis.title = element_text(family = "source-han-serif-cn", face = "plain", size = 10.54),
    legend.title = element_text(family = "source-han-serif-cn", face = "plain", size = 10.54),
    axis.ticks = element_line(colour = "black"),
    legend.text = element_text(family = "serif", size = 10.54),
    axis.text = element_text(family = "serif", size = 10.54),    
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.2)
  )
```


## 英文

```{r pressure, echo=TRUE, fig.cap="西文衬线字体"}
op <- par(family = "serif", mar = c(4,4,.5,.5))
plot(pressure)
par(op)
```


```{r fig.showtext=TRUE,dev='pdf',eval=FALSE}
library(showtext)
showtext_auto()
cairo_pdf(file = "demo_times.pdf", width = 8, height = 7, pointsize = 16)
pdf(file = "demo_times.pdf", width = 8, height = 7, pointsize = 16)
op <- par(mar = c(4, 4, .5, .5))
plot(pressure, xlab = "", ylab = "", family = "Times") # Times
# plot(pressure, xlab = "", ylab = "", family = "sans") # arial
title(xlab = "温度", ylab = "压力", family = "source-han-serif-cn")
par(op)
dev.off()
```


```{r, fig.cap="Times New Roman字体"}
op <- par(mar = c(4, 4, .5, .5))
plot(pressure, xlab = "", ylab = "", family = "Times") # Times
par(op)
```

pdf 设备可用字体

```{r}
names(pdfFonts())
```

## 艺术字体

# 公式

- https://github.com/wch/fontcm
- tikzDevice
- 默认 serif
- https://github.com/wch/extrafont
