--- 
title: "一个迷你的例子"
author: "黄湘云"
date: "`r Sys.Date()`"
thanks: "Yihui Xie"
site: bookdown::bookdown_site
documentclass: ctexbook
bibliography: [book.bib, packages.bib]
biblio-style: unsrt
lof: yes
lot: yes
graphics: yes
tables: yes
link-citations: yes
links-as-notes: no
colorlinks: yes
natbiboptions: super,square
classoption: "hyperref, a4paper, UTF8, zihao = -4, linespread = 1.3"
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# 准备

这个项目只能在 Windows 下用 pdfLaTeX 编译，适用于抱着 pdfLaTeX 和 Windows 就像考拉抱着树那样的用户。

- 四款中文字体和 Times New Roman 只因 Windows 才有
- Pandoc 的 LaTeX 模板
- bookdown [@xie2016] 分章节组织 R Markdown 文件
- knitr [@xie2015] 转化源文件为 markdown 文件，执行源文档包含的代码块，返回输出结果
- Pandoc 调用 pdfLaTeX 生成 pdf 文档

```{r}
devtools::session_info("bookdown")
```



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
